### ISSUE TITLE
UUnable to install 'DiemasMichiels.emulate';

### ISSUE THREAD

**Issue by moulichandu** [DiemasMichiels/Emulator#1]
I tried to install this plugin it given error

Unable to install 'DiemasMichiels.emulate'; there is no available version compatible with VS Code '1.21.1'.

**Comment by DiemasMichiels** [comment]
You are right the extensions is only available in VS Code 1.22.0 and above.

I'll check if which version below it I can support.

**Comment by moulichandu** [comment]
Thanks you, I will update my IDE
