### ISSUE TITLE
Nothing happens after the toast shows up saying "Emulator is booting up ..."

### ISSUE THREAD

**Issue by itsmasud** [DiemasMichiels/emulator#10]
I have followed the instructions:
Open command palette Cmd-Shift-P -> Type Emulator
--> select Emulator
--> select View android emulators
--> I chose one of the options out of the two item in the list.
I am getting the message "Emulator is booting up ..." and the emulator is not opening.

**Comment by Hankahn** [comment]
@itsmasud I was having the same issue. My issues was I was pointing the extension at the emulator.exe in the tools directory of the Android SDK and you need to point it at the emulator.exe in the emulator folder of the Android SDK.

**Comment by gotama** [comment]
@Hankahn where do you change the setting to point to the correct emulator?

**Comment by Hankahn** [comment]
@itsmasud, I updated the setting in VSCODE called "emulator.emulatorPath". I had originally set it to C:\Users\<your username>\AppData\Local\Android\Sdk\tools\emulator.exe but changed it to C:\Users\Shawn\AppData\Local\Android\Sdk\emulator\emulator.exe which is where the correct emulator.exe is located. I am on windows so your paths may be different if you are on a mac.

**Comment by mikaoelitiana** [comment]
@Hankahn @itsmasud changing `emulator.emulatorPath` in Mac didn't solve this for me. Any other suggestion?

**Comment by mikaoelitiana** [comment]
In fact I just found what was wrong. I tryed to launch the emulator from Android Studio and a message appeared telling me to delete the lock file.
I launched command `rm ~/.android/avd/Nexus_5X_API_26.avd/*.lock` and launched the emulator successfully then (You have to change the name of the avd according to you own ).

**Comment by DiemasMichiels** [comment]
Updated errors in version v1.0.0
