### ISSUE TITLE
Where do you type the line emulator.emulatorPath": "~/Library/Android/sdk/tools/emulator in the settings?

### ISSUE THREAD

**Issue by drtennan** [DiemasMichiels/emulator#11]
Hi, I'm not sure where to type the line: emulator.emulatorPath": "~/Library/Android/sdk/tools/emulator in the settings. 

Thanks!

**Comment by Joon-S** [comment]
File -> Preferences -> Setting -> User Setting -> Extensions -> Emulator Configuration
Good luck!

**Comment by DiemasMichiels** [comment]
Thanks Joon-S, I added it to the readme for better understanding!
