### ISSUE TITLE
x86 emulators not starting up on Mac

### ISSUE THREAD

**Issue by 540Grunkspin** [DiemasMichiels/emulator#12]
By adding the `emulator.emulatorPath` provide in the README the emulator will start non x86 emulators just fine. But if you want x86 i would recommend adding

```bash
export ANDROID_SDK=$HOME/Library/Android/sdk
export PATH=$ANDROID_SDK/emulator:$ANDROID_SDK/tools:$PATH
```

For Mac this will work for both types of emulators. I can create a PR for this but I am not sure how this works on windows. Have anyone tried?

**Comment by mthahzan** [comment]
Same issue here on my Mac. Nothing happens after the toast shows up saying "Emulator is booting up ...". Did you find a way to fix this?

**Comment by 540Grunkspin** [comment]
I did write the solution. Add the exports to your `.bash_profile file and then change the android emulator path in the  vscode config to just say `emulator`.

The problem is that some of the files needed to run the hardware accelerated emulator are in the tools directory. I might submit a patch for this at a later point. If I find the time for it since it should be able to modify the path to include the tools directory when running the emulator command from vscode.
