### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by haku-kiro** [DiemasMichiels/emulator#16]
Hi, I've set up android emulators using android studio on linux. The extension is able to pick up the the emulators that I've created, but when trying to start them - the message 'Emulator is booting up' shows, disappears, and it seems like nothing happens after that. 
As a side note, the emulators run in android studio.

Am I doing something wrong - or is the support for linux limited ? 

Let me know if I need to provided any other information.

**Comment by DiemasMichiels** [comment]
Hey @haku-kiro,

With linux you mean not macOS correct? If yes, which linux distro are you using?
I haven't checked nor supported linux in the past but I'm happy to do so. I'll check if I can setup a linux machine to test it and see what's wrong.
Feel free to contribute yourself :)

Thanks for logging the issue.

**Comment by DiemasMichiels** [comment]
Hey @haku-kiro 
What path did you use for your android emulator.
@JarrodCColburn just made a PR how a path on linux works and added it to the readme:

`Linux: "emulator.emulatorPath": "~/Android/Sdk/emulator"`

Can you verify it is working if you change it to this?

**Comment by DiemasMichiels** [comment]
I assume this is working, closing the issue!
