### ISSUE TITLE
Errors shown when cancelling

### ISSUE THREAD

**Issue by carolitascl** [DiemasMichiels/emulator#2]
The extension show errors when cancelling to start an emulator

1) Error when cancelling before choosing Android or iOS
"Failed the select OS version"

2) Error when cancelling after choosing Android or iOS
"Emulator failed to boot"

When you cancel, no errors should be shown

Thanks! Great work!

**Comment by DiemasMichiels** [comment]
You are right!
Correct error handling still needs to be made.

**Comment by DiemasMichiels** [comment]
Updated errors in version v1.0.0
