### ISSUE TITLE
[Request] Show iOS Version

### ISSUE THREAD

**Issue by fjcaetano** [DiemasMichiels/emulator#24]
If there are multiple iOS versions installed, some iOS simulators may appear duplicated. It'd be interesting to show the iOS version next to the simulator name as happens in Xcode

![image](https://user-images.githubusercontent.com/1066295/62564620-85edce00-b85b-11e9-80e8-a5a8a75da527.png)

If you think this would be interesting, I'm more than happy to work on a PR.

**Comment by DiemasMichiels** [comment]
That's indeed a good thing.
I'm was just implementing some other features so I added this too.
It will be added in the next release which is coming soon!

Thanks for the issue!

**Comment by DiemasMichiels** [comment]
New version 1.3.0 released! This feature is now added.
