### ISSUE TITLE
Exception if path has spaces

### ISSUE THREAD

**Issue by xXpc-freakXx** [DiemasMichiels/emulator#26]
Hi, my android sdk is located on "D:\Program Files (x86)\Android\android-sdk" and when I set the emulator path for windows to "%ANDROID_HOME%\\emulator" or the full path, then I become the followed exception:

> Error: Command failed: D:\Program Files (x86)\Android\android-sdk\emulator\emulator -list-avds 'D:\Program' is not recognized as an internal or external command, operable program or batch file.

I have tested with and without quotation marks, but nothing works.

**Comment by DiemasMichiels** [comment]
Fixed in next version (1.4.0)
