### ISSUE TITLE
Allow to hide the icon in the editor's title

### ISSUE THREAD

**Issue by moshfeu** [DiemasMichiels/emulator#27]
Currently it shows up when any editor is open. In most of the time it's not relevant.

**Comment by DiemasMichiels** [comment]
Will be fixed in next release!

**Comment by moshfeu** [comment]
Thanks!
FYI, you can close the issue with the commit that solves it: https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
