### ISSUE TITLE
Couldn't add path to VScode

### ISSUE THREAD

**Issue by saikrishnadas** [DiemasMichiels/emulator#30]
I use Windows 10, so I added the path "C:\\Users\\LENOVO\\AppData\\Local\\Android\\sdk\\emulator\\emulator.exe" to the vscode settings.

I have installed the sdk but still says that the path is wrong. When I looked deeper, I found that with adding the path and extra word addsin( "emulatore"  ) eventhough i dint mention it. 

I have attached the screenshot of the error.

![Screenshot (59)](https://user-images.githubusercontent.com/30836867/80682751-b3ad2e00-8ae0-11ea-897d-7b69e478ac04.png)

**Comment by DiemasMichiels** [comment]
Hi,

I looked at your path try removing `emulator.exe` of your path.  
It should look like this:  
`C:\\Users\\LENOVO\\AppData\\Local\\Android\\sdk\\emulator`

**Comment by saikrishnadas** [comment]
I tried removing it,

When i ran the path shows like this : C:\\Users\\LENOVO\\AppData\\Local\\Android\\sdk\\emulator\\emulator

**Comment by devemanager** [comment]
my error is the same

**Comment by DiemasMichiels** [comment]
That is normal, the application adds the /emulator on its own. You can always try in your console to see if you actually have the correct path by running:
`"C:\Users\LENOVO\AppData\Local\Android\Sdk\emulator\emulator" -list-avds`

Does this issue still occur?

**Comment by DiemasMichiels** [comment]
This issue is being closed as inactive.
