### ISSUE TITLE
Readme contains windows path with \\emulator.exe

### ISSUE THREAD

**Issue by janKir** [DiemasMichiels/emulator#31]
In the README, the emulator path for windows ends with `\\emulator.exe`:

```
Windows: "emulator.emulatorPathWindows":
      "<yourAndroidHome>\\Sdk\\emulator\\emulator.exe"
      or
      "C:\\Users\\<yourUsername>\\AppData\\Local\\Android\\Sdk\\emulator\\emulator.exe"
```
But it does only work without the trailing `\\emulator.exe`. Also, the setting description says to use the path to the directory: `The absolute path of the Android directory on your Windows containing the emulator scrip`.

**Comment by DiemasMichiels** [comment]
Thanks for the issue, updated the readme and settings description.
