### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by RomanKornev** [DiemasMichiels/emulator#34]
My path and environment variables are set correctly.
![image](https://user-images.githubusercontent.com/5807561/96519311-5f0b9400-1275-11eb-9f0a-004565923f90.png)
I can launch the emulator just fine with `flutter emulator` command, but not using this extension.

**Comment by DiemasMichiels** [comment]
Hello, make sure to extually set your Android path in the VScode settings.

Check the readme on how to do it.

**Comment by DiemasMichiels** [comment]
This issue is being closed as inactive / resolved.
