### ISSUE TITLE
Not possible to use -platform qemu2 in emulator start

### ISSUE THREAD

**Issue by jnitecki** [DiemasMichiels/emulator#38]
The recommended platform for emulator is now qemu2 rather than classic (which is a default if no -platform is specified). At least on my environment only qemu2 is configured, so attempt to launch the Android emulator results with:
**PANIC: Missing emulator engine program for 'x86' CPU.**
And verbose log shows: 
_emulator:Looking for emulator-x86 to emulate 'x86' CPU
emulator:Probing program: xxxxxx/emulator-x86.exe
PANIC: Missing emulator engine program for 'x86' CPU._

The quick solution was to add _-platform qemu2_ in constants.js, but it would be great if ability to pass additional invocation parameters to emulator will be added, there are more options there and maybe someone else will stumble on need of another one.

```
exports.ANDROID_COMMANDS = {
  LIST_AVDS: ' -list-avds',
  RUN_AVD: ' -engine qemu2 -avd ',
  RUN_AVD_COLD: ' -engine qemu2 -no-snapshot-load -avd '
}
```

**Comment by DiemasMichiels** [comment]
Hi thanks for your issue,

We have been very lucky since Sableange made a fix for this in pull request #41
I have added it to the codebase and released a new version: 1.5.0.

Check it out and if you have any feedback feel free to open more issues.
