### ISSUE TITLE
Provide a good default for the Android emulator on Windows

### ISSUE THREAD

**Issue by Tyriar** [DiemasMichiels/emulator#4]
This happens when you run Emulator without setting `emulator.emulatorPath`:

![image](https://user-images.githubusercontent.com/2193314/44949445-377fb600-ade6-11e8-883c-bd10f32da284.png)

**Comment by DiemasMichiels** [comment]
There will now be an error shown when the path is wrong. Didn't find a way to have a default for different operating systems.

Updated errors in version v1.0.0
