### ISSUE TITLE
Something went wrong fetching you Android emulators! Make sure your path is correct. 

### ISSUE THREAD

**Issue by erickalexandergonzalez** [DiemasMichiels/emulator#42]
I can´t run the emulator.  i have this error:
Try running this command in your terminal: "C:\Users\erick\AppData\Local\Android\Sdk\emulator\emulator.exe\emulator" -list-avds

i ran this sentence its seems everything is ok. Help me, please

"C:\Users\erick\AppData\Local\Android\Sdk\emulator\emulator.exe\emulator" -list-avds
Pixel_4_API_30
![emulator](https://user-images.githubusercontent.com/89319266/130334503-52d78dcf-e78a-455c-a8f7-39e410c658a8.JPG)

**Comment by DiemasMichiels** [comment]
Hello, the windows emulator path in the readme was wrong, this is now updated.

Pleasy try again with: `C:\Users\erick\AppData\Local\Android\Sdk\emulator` set as your `Emulator Path Windows` in the VSCode settings.

Thanks for your issue.

**Comment by erickalexandergonzalez** [comment]
Tks ......
