### ISSUE TITLE
Show unexpected errors when running AVD to the user

### ISSUE THREAD

**Issue by Tyriar** [DiemasMichiels/emulator#7]
Currently an error shows in devtools only.

![image](https://user-images.githubusercontent.com/2193314/44949570-300ddc00-ade9-11e8-884d-95e9ac5a9cce.png)

Root cause:

![image](https://user-images.githubusercontent.com/2193314/44949572-369c5380-ade9-11e8-964a-a3618ae18b8b.png)

**Comment by Tyriar** [comment]
This is how Android Studio handles it:

![image](https://user-images.githubusercontent.com/2193314/44949581-63e90180-ade9-11e8-9e2d-4a7918eae200.png)

**Comment by DiemasMichiels** [comment]
HI @Tyriar 
Thanks for reviewing my extension and commenting about things that are still missing.
I greatly appreciate it!

**Comment by DiemasMichiels** [comment]
Updated errors in version v1.0.0
